
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alons
 */
public class bobj extends java.awt.Frame {

    Lista l;
    Lista p;
    Lista h;

    /**
     * Creates new form bobj
     */
    public bobj(Lista l, Lista p, Lista h) {
        initComponents();
        this.l = l;
        this.p = p;
        this.h = h;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NP = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombreP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidadP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precioP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mPesados = new javax.swing.JRadioButton();
        mPequeños = new javax.swing.JRadioButton();
        herra = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        fechaAd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaexp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        IDBusca = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton1.setText("Menú Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscador de Objetos");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID del producto:");

        jLabel3.setText("Nombre del Producto:");

        NP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPActionPerformed(evt);
            }
        });

        search.setText("Buscar");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre: ");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Precio:");

        precioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioPActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo:");

        buttonGroup1.add(mPesados);
        mPesados.setText("Materiales Pesados");

        buttonGroup1.add(mPequeños);
        mPequeños.setText("Materiales Pequeños");

        buttonGroup1.add(herra);
        herra.setText("Herramientas");

        jLabel8.setText("Fecha de Adquisición:");

        jLabel9.setText("Fecha de Expiración");

        fechaexp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fechaexp.setForeground(new java.awt.Color(204, 0, 0));
        fechaexp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(search)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(IDP)
                                        .addComponent(NP, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mPesados)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mPequeños)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(herra))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaAd, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel10)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaexp)
                                    .addComponent(IDBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mPesados)
                    .addComponent(mPequeños)
                    .addComponent(herra))
                .addGap(18, 18, 18)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fechaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(fechaexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(IDBusca))
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NPActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if (NP.getText().isEmpty()) {
            int bid = Integer.parseInt(IDP.getText());
            

            if (mPesados.isSelected()) {
                int test = 0;
                int tes2 = 0;
                test = l.contarElementos1();
                if (test > 0) {
                    tes2 = l.IDUltimo();
                    if (bid <= tes2) {
                        int num = l.contarElementos1();
                        
                        int pos = l.binSearchRec(bid, 0, num-1);
                                                                                                                          
                        String name = l.buscarNombre(pos);
                        int cantidad = l.buscarCantidad(pos);
                        int precio = l.buscarPrecio(pos);
                        String laFecha = l.buscarFecha(pos);
                        nombreP.setText(name);
                        cantidadP.setText("" + cantidad);
                        precioP.setText("$" + precio);
                        fechaAd.setText(laFecha);
                        String fechaCadu = fechaCaducidad(laFecha);
                        fechaexp.setText(fechaCadu);
                        IDBusca.setText(IDP.getText());
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                }
            }
            if (mPequeños.isSelected()) {
                int tes2 = 0;
                int test = 0;
                test = p.contarElementos1();
                if (test > 0) {
                    tes2 = p.IDUltimo();
                    if (bid <= tes2) {
                        int pos = p.buscarEn(bid);
                        String name = p.buscarNombre(pos);
                        int cantidad = p.buscarCantidad(pos);
                        int precio = p.buscarPrecio(pos);
                        String laFecha = p.buscarFecha(pos);
                        nombreP.setText(name);
                        cantidadP.setText("" + cantidad);
                        precioP.setText("$" + precio);
                        fechaAd.setText(laFecha);
                        String fechaCadu = fechaCaducidad(laFecha);
                        fechaexp.setText(fechaCadu);
                    } else {
                        JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                }

            }
            if (herra.isSelected()) {
                int test = 0;
                int tes2 = 0;
                test = h.contarElementos1();
                if (test > 0) {
                    tes2 = h.IDUltimo();
                    if (bid <= tes2) {
                        int pos = h.buscarEn(bid);
                        String name = h.buscarNombre(pos);
                        int cantidad = h.buscarCantidad(pos);
                        int precio = h.buscarPrecio(pos);
                        String laFecha = h.buscarFecha(pos);
                        nombreP.setText(name);
                        cantidadP.setText("" + cantidad);
                        precioP.setText("$" + precio);
                        fechaAd.setText(laFecha);
                        String fechaCadu = fechaCaducidad(laFecha);
                        fechaexp.setText(fechaCadu);
                    } else {
                        JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                }

            }
        } else {
            String name2 = NP.getText();
            if (mPesados.isSelected()) {
                int test = 0;
                test = l.contarElementos1();
                if (test > 0) {
                    int pos = l.buscarConNombre(name2);
                    String name = l.buscarNombre(pos);
                    int cantidad = l.buscarCantidad(pos);
                    int precio = l.buscarPrecio(pos);
                    String laFecha = l.buscarFecha(pos);
                    nombreP.setText(name);
                    cantidadP.setText("" + cantidad);
                    precioP.setText("$" + precio);
                    fechaAd.setText(laFecha);
                    String fechaCadu = fechaCaducidad(laFecha);
                    fechaexp.setText(fechaCadu);
                    int elID = l.buscarID(pos);
                    IDBusca.setText("" + elID);
                } else {
                    JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                }
            }
            if (mPequeños.isSelected()) {
                int test = 0;
                test = l.contarElementos1();
                if (test > 0) {
                    int pos = p.buscarConNombre(name2);
                    String name = p.buscarNombre(pos);
                    int cantidad = p.buscarCantidad(pos);
                    int precio = p.buscarPrecio(pos);
                    String laFecha = p.buscarFecha(pos);
                    nombreP.setText(name);
                    cantidadP.setText("" + cantidad);
                    precioP.setText("$" + precio);
                    fechaAd.setText(laFecha);
                    String fechaCadu = fechaCaducidad(laFecha);
                    fechaexp.setText(fechaCadu);
                    int elID = p.buscarID(pos);
                    IDBusca.setText("" + elID);
                } else {
                    JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                }

            }
            if (herra.isSelected()) {
                int test = 0;
                test = l.contarElementos1();
                if (test > 0) {
                    int pos = h.buscarConNombre(name2);
                    String name = h.buscarNombre(pos);
                    int cantidad = h.buscarCantidad(pos);
                    int precio = h.buscarPrecio(pos);
                    String laFecha = h.buscarFecha(pos);
                    nombreP.setText(name);
                    cantidadP.setText("" + cantidad);
                    precioP.setText("$" + precio);
                    fechaAd.setText(laFecha);
                    String fechaCadu = fechaCaducidad(laFecha);
                    fechaexp.setText(fechaCadu);
                    int elID = h.buscarID(pos);
                    IDBusca.setText("" + elID);
                } else {
                    JOptionPane.showMessageDialog(null, "El objeto no existe. Verifique los datos.");
                }

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void precioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /* new bobj().setVisible(true);*/
            }
        });
    }

    public String fechaCaducidad(String fechaAd) {
        int dia = Integer.parseInt(fechaAd.substring(0, 2));
        int mes = Integer.parseInt(fechaAd.substring(3, 5));
        int año = Integer.parseInt(fechaAd.substring(6, 10));
        if (mes > 6) {
            año = año + 1;
        }
        mes = mes + 6;

        String resul = "";
        if (mes > 12) {
            mes = mes - 12;
            resul = "" + dia + "/" + mes + "/" + año;
        }
        if (mes < 10 && dia < 10) {
            resul = "0" + dia + "/" + "0" + mes + "/" + año;
        }
        if (mes < 10 && dia > 10) {
            resul = "" + dia + "/0" + mes + "/" + año;
        }
        if (dia < 10 && mes > 10) {
            resul = "0" + dia + "/" + mes + "/" + año;
        }
        return resul;
    }

    public int binarySearchl(int iValorBuscar, int num) {
        int resul=l.binSearchRec(iValorBuscar, 0, num );
        return resul;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDBusca;
    private javax.swing.JTextField IDP;
    private javax.swing.JTextField NP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantidadP;
    private javax.swing.JTextField fechaAd;
    private javax.swing.JTextField fechaexp;
    private javax.swing.JRadioButton herra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton mPequeños;
    private javax.swing.JRadioButton mPesados;
    private javax.swing.JTextField nombreP;
    private javax.swing.JTextField precioP;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
