
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ed
 */
public class Delete extends javax.swing.JFrame {

    Lista l;
    Lista p;
    Lista h;

    /**
     * Creates new form Delete
     */
    public Delete(Lista l, Lista p, Lista h) {
        initComponents();
        this.l = l;
        this.p = p;
        this.h = h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sName = new javax.swing.JTextField();
        iCant = new javax.swing.JTextField();
        iPrice = new javax.swing.JTextField();
        sType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Del Objeto:");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Objeto");

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Precio:");

        jLabel6.setText("Tipo:");

        jButton2.setText("Menú Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDO, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addComponent(iPrice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iCant, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int bid = Integer.parseInt(IDO.getText());
        if (bid >= 1000 && bid < 2000) {
            int pos = l.buscarEn(bid);
            String name = l.buscarNombre(pos);
            int cantidad = l.buscarCantidad(pos);
            int precio = l.buscarPrecio(pos);
            String laFecha = l.buscarFecha(pos);
            sName.setText(name);
            iCant.setText("" + cantidad);
            iPrice.setText("" + precio);
            sType.setText("Materiales Pesados");
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                ex.printStackTrace();
            }
            int resp = JOptionPane.showConfirmDialog(null, "El objeto será eliminado definitivamente. ¿Desea continuar?");
            if (resp == 0) {
                l.borrarEn(pos);
                sName.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                iCant.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                iPrice.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                sType.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                IDO.setText("");
                JOptionPane.showMessageDialog(rootPane, "Objeto Eliminado");
            }
        } else if (bid >= 2000 && bid < 3000) {
            int pos = p.buscarEn(bid);
            String name = p.buscarNombre(pos);
            int cantidad = p.buscarCantidad(pos);
            int precio = p.buscarPrecio(pos);
            String laFecha = p.buscarFecha(pos);
            sName.setText(name);
            iCant.setText("" + cantidad);
            iPrice.setText("" + precio);
            sType.setText("Materiales Pequeños");
            int resp = JOptionPane.showConfirmDialog(null, "El objeto será eliminado definitivamente. ¿Desea continuar?");
            if (resp == 0) {
                p.borrarEn(pos);
                sName.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                iCant.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                iPrice.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                sType.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                IDO.setText("");
                JOptionPane.showMessageDialog(rootPane, "Objeto Eliminado");
            }
        } else {
            int pos = h.buscarEn(bid);
            String name = h.buscarNombre(pos);
            int cantidad = h.buscarCantidad(pos);
            int precio = h.buscarPrecio(pos);
            String laFecha = h.buscarFecha(pos);
            sName.setText(name);
            iCant.setText("" + cantidad);
            iPrice.setText("" + precio);
            sType.setText("Herramientas");
            int resp = JOptionPane.showConfirmDialog(null, "El objeto será eliminado definitivamente. ¿Desea continuar?");
            if (resp == 0) {
                h.borrarEn(pos);
                sName.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                iCant.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                iPrice.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                sType.setText("");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) { //Este Try Y catch es simplemente para parar el programa por medio segundo y poder ver los cambios realizados
                    ex.printStackTrace();
                }
                IDO.setText("");
                JOptionPane.showMessageDialog(rootPane, "Objeto Eliminado");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDO;
    private javax.swing.JTextField iCant;
    private javax.swing.JTextField iPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sType;
    // End of variables declaration//GEN-END:variables
}
