
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ed
 */
public class Login extends javax.swing.JFrame {

    Lista l;
    int iCont = 1;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sUsuario = new javax.swing.JTextField();
        sContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        welcome.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        welcome.setText("WELCOME TO AJAR");

        jLabel2.setText("Usuario: ");

        jLabel3.setText("Contraseña:");

        sUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUsuarioActionPerformed(evt);
            }
        });

        sContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sContraseñaActionPerformed(evt);
            }
        });

        jButton1.setText("Accesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(165, 165, 165))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(sContraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(welcome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcome)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Usuario = sUsuario.getText();
        String Contraseña = sContraseña.getText();
        boolean test = false;
        String UsuariosyContras[][] = new String[4][4];
        UsuariosyContras[0][0] = "EduardoMata";
        UsuariosyContras[0][1] = "ErAa4";
        UsuariosyContras[1][0] = "RuthOrtiz";
        UsuariosyContras[1][1] = "ErAa4";
        UsuariosyContras[2][0] = "AlonsoParra";
        UsuariosyContras[2][1] = "ErAa4";
        UsuariosyContras[3][0] = "AnaMartinez";
        UsuariosyContras[3][1] = "ErAa4";
        if (iCont <= 4) {
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 3; j++) {
                    if (Usuario.equals(UsuariosyContras[i][0])) {
                        if (Contraseña.equals(UsuariosyContras[i][j])) {
                            Inventario IN = new Inventario();
                            IN.setVisible(true);
                            this.dispose();
                            test = true;
                        }
                    }
                }

            }
        } else {
            sUsuario.setVisible(false);
            sContraseña.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "EXCEDIÓ NÚMERO DE INTENTOS PERMITIDOS");
            welcome.setText("AJAR HAS BEEN BLOCKED");
        }
        if (test == false && iCont <= 4) {
            JOptionPane.showMessageDialog(rootPane, "ERROR");
            sUsuario.setText("");
            sContraseña.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sContraseñaActionPerformed
        String Usuario = sUsuario.getText();
        String Contraseña = sContraseña.getText();
        boolean test = false;

        String UsuariosyContras[][] = new String[4][4];
        UsuariosyContras[0][0] = "Eduardo.Mata";
        UsuariosyContras[0][1] = "AJAR.1";
        UsuariosyContras[1][0] = "Ruth.Ortiz";
        UsuariosyContras[1][1] = "AJAR.2";
        UsuariosyContras[2][0] = "AP";
        UsuariosyContras[2][1] = "12";
        UsuariosyContras[3][0] = "Ana.Martinez";
        UsuariosyContras[3][1] = "AJAR.4";
        if (iCont <= 4) {
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 3; j++) {
                    if (Usuario.equals(UsuariosyContras[i][0])) {
                        if (Contraseña.equals(UsuariosyContras[i][j])) {
                            Inventario IN = new Inventario();
                            IN.setVisible(true);
                            this.dispose();
                            test = true;
                        }
                    }
                }

            }
        } else {
            sUsuario.setVisible(false);
            sContraseña.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "EXCEDIÓ NÚMERO DE INTENTOS PERMITIDOS");
            welcome.setText("AJAR HAS BEEN BLOCKED");
        }
        if (test == false) {
            JOptionPane.showMessageDialog(rootPane, "ERROR");
            sUsuario.setText("");
            sContraseña.setText("");
            iCont = iCont + 1;
        }

// TODO add your handling code here:
    }//GEN-LAST:event_sContraseñaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField sContraseña;
    private javax.swing.JTextField sUsuario;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
